// All UI text in one place (spec §9). Thai default; add `en` later with the same keys.
export const t = {
  brand: 'HUNT DASHBOARD',
  quest: 'เควส',
  hunting: (n: number) => `ล่า ${n} ตัว`,
  phase: { day: 'กลางวัน', night: 'กลางคืน', dusk: 'พลบค่ำ', dawn: 'รุ่งเช้า' },
  link: { connecting: 'รอเชื่อมต่อ…', offline: 'ไม่ได้เชื่อมต่อเกม', stale: 'ข้อมูลไม่อัปเดต', live: 'เชื่อมต่อเกมแล้ว' },
  waitingBridge: 'รอเชื่อมต่อ…',
  waitingBridgeHint: 'เปิด bridge ด้วย npm run dev หรือ npm run bridge',
  waitingGame: 'รอข้อมูลจากเกม…',
  notInQuest: 'ยังไม่ได้อยู่ในเควส',
  noMonster: 'ยังไม่พบมอนสเตอร์',
  size: (p: number) => `ขนาด ${p}%`,
  crown: { gold: 'มงกุฎทอง', silver: 'มงกุฎเงิน', mini: 'มงกุฎเล็ก' },
  enraged: 'โกรธ',
  capture: 'จับได้แล้ว · ใช้กับดักได้',
  done: 'ล่าสำเร็จ',
  wounds: 'แผลที่เปิด',
  breaks: 'ทำลายแล้ว',
  partsTitle: 'ส่วนที่ทำลายได้',
  partsSort: 'เรียงตามใกล้ทำลาย',
  partLeft: (p: number) => `อีก ${p}%`,
  partBroken: 'ทำลายแล้ว',
  noParts: 'ไม่มีส่วนที่ทำลายได้',
  ailmentsTitle: 'สถานะผิดปกติ',
  ailment: {
    paralysis: 'อัมพาต', poison: 'พิษ', stun: 'สตัน', sleep: 'หลับ', blast: 'ระเบิด',
    exhaust: 'เหนื่อย', ride: 'ขี่', flash: 'แฟลช', pitfall: 'ติดกับดัก',
  } as Record<string, string>,
  noAilments: 'ยังไม่มีข้อมูล',
  ailmentActive: 'ทำงาน',
  // "do this now" panel
  nowTitle: 'ตอนนี้',
  nowEmpty: 'ไม่มีอะไรเร่งด่วน · ตีจุดอ่อนต่อ',
  now: {
    capture: ['จับได้แล้ว', 'วางกับดัก + ยาสลบ'],
    ailment: 'โจมตีเต็มที่',
    enrage: ['มอนโกรธ', 'ระวังท่าแรง'],
    part: (name: string, p: number) => [`${name} อีก ${p}%`, 'ใกล้ทำลาย'],
    buff: (name: string) => [name, 'ใกล้หมด'],
    buildup: (name: string, p: number) => [`${name} ${p}%`, 'ใกล้ติดสถานะ'],
    buffMissing: (name: string) => [`${name} หมด`, 'กินใหม่'],
  },
  // weak spots / elements
  weakTitle: 'จุดอ่อน',
  elementTitle: 'ธาตุ',
  element: { fire: 'ไฟ', water: 'น้ำ', thunder: 'สายฟ้า', ice: 'น้ำแข็ง', dragon: 'มังกร' } as Record<string, string>,
  scar: { tear: 'แผล', raw: 'แผลสด' } as Record<string, string>,
  questRemain: (s: string) => `เหลือ ${s}`,
  buffsTitle: 'ตัวเรา',
  vitals: { hp: 'HP', stamina: 'สตามินา' },
  crit: 'คริ',
  cooldown: 'คูลดาวน์',
  critTitle: 'อัตราคริติคอล (จำนวนครั้งที่คริ ÷ จำนวน hit)',
  dpsChart: 'กราฟ DPS ช่วง 15 วินาที: ทีม (ฟ้า) และเรา (ส้ม)',
  chart: {
    title: 'DPS ระหว่างเควส (เฉลี่ย 15 วิ)',
    team: 'ทั้งทีม',
    all: 'แสดงทั้งหมด',
    onlyMe: 'เฉพาะเรา',
    oldRecord: 'เควสนี้บันทึกก่อนมีข้อมูลรายคน: แสดงได้แค่ทั้งทีมกับเรา',
  },
  summary: {
    title: 'สรุปการล่า',
    time: 'เวลา',
    hpLeft: (p: number) => `HP เหลือ ${p}%`,
    procs: 'ติดสถานะ',
    hunter: 'นักล่า',
    damage: 'ดาเมจ',
    weak: 'โดนจุดอ่อน',
    uptime: 'Uptime บัฟ (% ของเวลาเควส)',
    history: 'ประวัติการล่า',
  },
  settings: {
    open: 'ตั้งค่า (S)',
    title: 'ตั้งค่า',
    sections: { general: 'ทั่วไป', discord: 'Discord', setup: 'การติดตั้ง', about: 'เกี่ยวกับ' } as Record<string, string>,
    display: 'หน้าจอ',
    advanced: 'ขั้นสูง',
    connection: 'การเชื่อมต่อ',
    version: 'เวอร์ชัน',
    source: 'ซอร์สโค้ดบน GitHub',
    port: 'พอร์ต bridge',
    scale: 'ขนาดหน้าจอ',
    sound: 'เสียงเตือน (จับได้ / ติดสถานะ / โกรธ / บัฟหมด)',
    soundMode: { off: 'ปิด', beep: 'บี๊บ', voice: 'พูด' } as Record<string, string>,
    voice: 'เสียงพูด',
    voiceRate: 'ความเร็วเสียงพูด',
    soundTest: 'ลองเสียง',
    noThaiVoice: 'เครื่องนี้ไม่มีเสียงภาษาไทย จะใช้เสียงบี๊บแทน · เพิ่มได้ที่ Windows Settings → Time & language → Speech',
    watchBuffs: 'เตือนเมื่อบัฟหมด',
    watchHint: 'เตือน (และพูด) เมื่อบัฟที่เลือกไม่ทำงานระหว่างเควส หลัง 20 วินาทีแรก · Mega นับรวมด้วย',
    panels: 'แสดงส่วนไหนบ้าง',
    panel: { now: 'ตอนนี้', parts: 'ส่วนที่ทำลายได้', ailments: 'สถานะผิดปกติ', buffs: 'ตัวเรา', damage: 'ดาเมจทีม' },
    reset: 'คืนค่าเริ่มต้น',
    discord: 'แสดงสถานะการล่าใน Discord',
    discordId: 'Application ID',
    discordStatus: {
      off: 'ปิดอยู่', connecting: 'กำลังเชื่อม Discord…', live: 'กำลังโชว์ใน Discord',
      error: 'เชื่อม Discord ไม่ได้ · เปิด Discord บนเครื่องนี้ หรือเช็ค Application ID',
    } as Record<string, string>,
    discordNothing: 'ยังไม่มีข้อมูลจากเกม',
    discordText: 'แก้ข้อความที่โชว์',
    discordTextHint: '{monster} = ชื่อมอน · {ailment} = สถานะ · {time} = เวลาเควส · HP ต่อท้ายให้เอง · เว้นว่าง = ค่าเดิม',
    discordTextReset: 'คืนข้อความเดิมทั้งหมด',
    discordTextKey: {
      hunt: 'กำลังล่า', enraged: 'มอนโกรธ', ailment: 'มอนติดสถานะ', dead: 'มอนตาย',
      captured: 'จับมอนได้', quest: 'ในเควส ยังไม่เจอมอน', camp: 'อยู่แคมป์', recent: 'หลังจบเควส',
    } as Record<string, string>,
    discordHint: 'สร้างที่ discord.com/developers → New Application แล้ว copy Application ID มาใส่ · ต้องเปิด Discord บนเครื่องนี้',
    close: 'ปิด (Esc)',
    hint: 'กด S เพื่อเปิด/ปิดหน้านี้ · ค่าถูกบันทึกในเครื่องนี้',
  },
  tabs: { hunt: 'การล่า', hunter: 'นักล่า', history: 'ประวัติ', key: 'สลับแท็บด้วยปุ่ม 1 / 2 / 3' },
  history: {
    title: 'ประวัติการล่า',
    count: (n: number, max: number) => `${n} / ${max} เควสล่าสุด`,
    empty: 'ยังไม่มีประวัติการล่า',
    emptyHint: 'จบเควสสักครั้ง แล้วจะขึ้นที่นี่ (เก็บ 20 เควสล่าสุด)',
    won: 'ล่าสำเร็จ',
    notWon: 'ยังไม่จบ / ยกเลิก',
    viewAll: (n: number) => `ดูประวัติทั้งหมด (${n})`,
  },
  hunter: {
    profile: 'นักล่า',
    hr: 'HR',
    weapon: 'อาวุธ',
    skills: 'สกิลที่ทำงาน',
    noSkills: 'ไม่มีสกิล',
    noProfile: 'ยังไม่มีข้อมูลตัวละคร · เปิดเกมแล้วรัน npm run install-lua ใหม่',
    stats: 'สถิติการล่า',
    monstersTitle: 'มอนที่ล่า',
    statsNote: (n: number) => `นับจาก ${n} เควสล่าสุดที่แอปนี้บันทึกไว้`,
    noHistory: 'ยังไม่มีประวัติ · จบเควสสักครั้งก่อน',
    hunts: 'เควส',
    totalTime: 'เวลารวม',
    totalDamage: 'ดาเมจรวม',
    avgDps: 'DPS เฉลี่ย',
    bestDps: 'DPS สูงสุด',
    monster: 'มอนสเตอร์',
    count: 'เจอ',
    slain: 'ล่าสำเร็จ',
    best: 'เร็วสุด',
  },
  setup: {
    title: 'การติดตั้ง',
    game: 'โฟลเดอร์เกม',
    noGame: 'ไม่พบ Monster Hunter Wilds ใน Steam',
    reframework: 'REFramework',
    catlib: '_CatLib',
    lua: 'สคริปต์ Hunt Dashboard',
    ok: 'พร้อม',
    missing: 'ยังไม่ได้ลง',
    luaState: { current: 'ล่าสุดแล้ว', updated: 'อัปเดตแล้ว', skipped: 'รอ REFramework', error: 'ติดตั้งไม่ได้' } as Record<string, string>,
    needs: 'แดชบอร์ดต้องใช้ REFramework และ _CatLib ในเกม ลงเองครั้งเดียวแล้วกดตรวจอีกครั้ง (สคริปต์ของแดชบอร์ดแอปลงให้เอง) ยังขาด:',
    getReframework: 'โหลด REFramework',
    getCatlib: 'หา _CatLib บน Nexus Mods',
    reset: 'สคริปต์ในเกมอัปเดตแล้ว ถ้าเกมเปิดอยู่ ให้กด Reset scripts ในเมนู REFramework (ScriptRunner) หรือเปิดเกมใหม่',
    recheck: 'ตรวจอีกครั้ง',
    dismiss: 'รับทราบ',
  },
  // watched buff groups (ids from WATCHABLE_BUFFS in logic.ts)
  buffGroup: {
    demondrug: 'Demondrug', armorskin: 'Armorskin', might: 'Might Seed / Pill', adamant: 'Adamant Seed / Pill',
    demon_powder: 'Demon Powder', hard_powder: 'Hardshell Powder', hot_drink: 'Hot Drink', cool_drink: 'Cool Drink',
    dash_juice: 'Dash Juice', immunizer: 'Immunizer',
  } as Record<string, string>,
  // spoken alerts (voice mode)
  say: {
    capture: 'จับได้แล้ว',
    enrage: (who?: string) => `${who ?? 'มอน'} โกรธ`,
    buffMissing: (name: string) => `${name} หมด`,
    test: 'จับได้แล้ว วางกับดัก',
  },
  // timeline on the summary chart
  events: {
    chip: 'เหตุการณ์',
    enrage: 'โกรธ', capture: 'เข้าเส้นจับได้', slain: 'ตาย', captured: 'จับได้', break: (part: string) => `ทำลาย${part}`,
    buffOut: (name: string) => `${name} หมด`,
    count: { enrage: 'โกรธ', ailment: 'ติดสถานะ', break: 'ทำลาย', buffOut: 'บัฟหมด' } as Record<string, string>,
  },
  update: {
    title: 'อัปเดต',
    auto: 'เช็คเวอร์ชันใหม่อัตโนมัติ',
    checkNow: 'เช็คตอนนี้',
    checking: 'กำลังเช็ค…',
    never: 'ยังไม่ได้เช็ค',
    failed: 'เช็คไม่ได้ (ออฟไลน์?)',
    upToDate: (v: string) => `ล่าสุดแล้ว (${v})`,
    available: (latest: string, current: string) => `มีเวอร์ชันใหม่ ${latest} (ตอนนี้ ${current})`,
    download: 'ดาวน์โหลด',
    later: 'ไว้ทีหลัง',
  },
  noBuffs: 'ไม่มีบัฟ',
  damageTitle: 'ดาเมจทีม',
  topDamage: 'ดาเมจสูงสุดในทีม',
  noDamage: 'ยังไม่มีดาเมจ',
};
