// All UI text in one place (spec §9). Thai default; add `en` later with the same keys.
export const t = {
  brand: 'HUNT DASHBOARD',
  quest: 'เควส',
  hunting: (n: number) => `ล่า ${n} ตัว`,
  phase: { day: 'กลางวัน', night: 'กลางคืน', dusk: 'พลบค่ำ', dawn: 'รุ่งเช้า' },
  link: { connecting: 'รอเชื่อมต่อ…', offline: 'ไม่ได้เชื่อมต่อเกม', stale: 'ข้อมูลไม่อัปเดต', live: 'เชื่อมต่อเกมแล้ว' },
  waitingBridge: 'รอเชื่อมต่อ…',
  waitingBridgeHint: 'เปิด bridge ด้วย npm run dev หรือ npm run bridge',
  waitingGame: 'รอข้อมูลจากเกม…',
  notInQuest: 'ยังไม่ได้อยู่ในเควส',
  noMonster: 'ยังไม่พบมอนสเตอร์',
  size: (p: number) => `ขนาด ${p}%`,
  crown: { gold: 'มงกุฎทอง', silver: 'มงกุฎเงิน', mini: 'มงกุฎเล็ก' },
  enraged: 'โกรธ',
  capture: 'จับได้แล้ว · ใช้กับดักได้',
  done: 'ล่าสำเร็จ',
  wounds: 'แผลที่เปิด',
  breaks: 'ทำลายแล้ว',
  partsTitle: 'ส่วนที่ทำลายได้',
  partsSort: 'เรียงตามใกล้ทำลาย',
  partLeft: (p: number) => `อีก ${p}%`,
  partBroken: 'ทำลายแล้ว',
  noParts: 'ไม่มีส่วนที่ทำลายได้',
  ailmentsTitle: 'สถานะผิดปกติ',
  ailment: {
    paralysis: 'อัมพาต', poison: 'พิษ', stun: 'สตัน', sleep: 'หลับ', blast: 'ระเบิด',
    exhaust: 'เหนื่อย', ride: 'ขี่', flash: 'แฟลช', pitfall: 'ติดกับดัก',
  } as Record<string, string>,
  noAilments: 'ยังไม่มีข้อมูล',
  ailmentActive: 'ทำงาน',
  // "do this now" panel
  nowTitle: 'ตอนนี้',
  nowEmpty: 'ไม่มีอะไรเร่งด่วน · ตีจุดอ่อนต่อ',
  now: {
    capture: ['จับได้แล้ว', 'วางกับดัก + ยาสลบ'],
    ailment: 'โจมตีเต็มที่',
    enrage: ['มอนโกรธ', 'ระวังท่าแรง'],
    part: (name: string, p: number) => [`${name} อีก ${p}%`, 'ใกล้ทำลาย'],
    buff: (name: string) => [name, 'ใกล้หมด'],
    buildup: (name: string, p: number) => [`${name} ${p}%`, 'ใกล้ติดสถานะ'],
  },
  // weak spots / elements
  weakTitle: 'จุดอ่อน',
  elementTitle: 'ธาตุ',
  element: { fire: 'ไฟ', water: 'น้ำ', thunder: 'สายฟ้า', ice: 'น้ำแข็ง', dragon: 'มังกร' } as Record<string, string>,
  scar: { tear: 'แผล', raw: 'แผลสด' } as Record<string, string>,
  questRemain: (s: string) => `เหลือ ${s}`,
  dataCredit: 'ข้อมูลมอน: mh-wilds.kerlos.in.th · keRLos',
  buffsTitle: 'บัฟของเรา',
  noBuffs: 'ไม่มีบัฟ',
  damageTitle: 'ดาเมจทีม',
  noDamage: 'ยังไม่มีดาเมจ',
};
